import {chromium} from 'playwright';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
await page.goto('http://127.0.0.1:5173/');
await page.waitForTimeout(500);
await page.mouse.wheel(0,600);
await page.waitForTimeout(100);const early=await page.evaluate(()=>scrollY);
await page.waitForTimeout(1000);const final=await page.evaluate(()=>scrollY);
if(!(early>0&&early<final&&Math.abs(final-600)<3))throw Error(`Wheel ${early} ${final}`);
await page.locator('header nav a[href="#solutions"]').first().click();await page.waitForTimeout(1100);
const top=await page.locator('#solutions').evaluate(e=>e.getBoundingClientRect().top);
if(Math.abs(top-95)>3)throw Error(`Anchor ${top}`);
const next=page.getByRole('button',{name:'Следующее решение'});
await next.click();if(await page.locator('#service-panel').getAttribute('data-solution')!=='iaas')throw Error('Next failed');
await next.hover();await page.waitForTimeout(250);
const colors=await next.evaluate(e=>({bg:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));
if(colors.bg!=='rgb(255, 255, 255)'||colors.color!=='rgb(0, 0, 0)')throw Error(JSON.stringify(colors));
await page.getByRole('button',{name:'Предыдущее решение'}).click();
if(await page.locator('#service-panel').getAttribute('data-solution')!=='colocation')throw Error('Previous failed');
console.log(JSON.stringify({early,final,top,colors,version:await page.evaluate(()=>window.lenisVersion)}));
await browser.close();
