import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'test-results/desktop.png'});
await page.getByRole('tab',{name:'IaaS / Облако'}).click();
await page.getByRole('tabpanel').getByRole('heading',{name:'Облачная инфраструктура'}).waitFor();
await page.locator('#choose-service').click();
if(await page.locator('select').inputValue()!=='Облачная инфраструктура')throw Error('Service selection not applied');
await page.getByLabel('Ваше имя').fill('Проверка');await page.getByLabel('Рабочий email').fill('test@example.com');
const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать бриф проекта'}).click();const download=await downloadEvent;
if(download.suggestedFilename()!=='TAU-CLOUD-project-brief.txt')throw Error('Brief download missing');
await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
await page.mouse.wheel(0,1700);await page.waitForTimeout(500);
await page.screenshot({path:'test-results/story-middle.png'});
if(await page.locator('.chapter.active').getAttribute('data-chapter')==='0')throw Error('Scroll chapter did not change');
await page.mouse.wheel(0,-2000);await page.waitForTimeout(500);
if(await page.locator('.chapter.active').getAttribute('data-chapter')!=='0')throw Error('Reverse scrolling failed');
await page.screenshot({path:'test-results/full-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(250);
await page.screenshot({path:'test-results/mobile.png'});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
await page.getByRole('button',{name:'Открыть меню'}).click();await page.locator('#mobile-nav').getByRole('link',{name:'Решения'}).click();
if(await page.locator('#mobile-nav').isVisible())throw Error('Mobile menu not closed');
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(200);
if(await page.locator('#film').evaluate(e=>getComputedStyle(e).opacity)!=='0')throw Error('Reduced motion film visible');
await page.goto('http://127.0.0.1:5173/style-tile.html');await page.getByText('STYLE TILE / 01').waitFor();
console.log(JSON.stringify({passed:true,errors,viewports:['1440x900','390x844'],checks:['service tabs','service to form','brief download','native forward/reverse scroll','mobile overflow','mobile navigation','reduced motion','style tile']}));
await browser.close();if(errors.length)process.exit(1);
