import {readFileSync,writeFileSync} from 'node:fs';
const path='src/main.js';
let s=readFileSync(path,'utf8');
s=s.replace('href="#solutions">Найти своё решение ${arrow}</a></article>','href="${i<3?\'#contact\':\'#solutions\'}" ${i<3?\'data-colocation-cta\':\'\'}>${i<3?\'Обсудить размещение\':\'Найти своё решение\'} ${arrow}</a></article>');
s=s.replace('Масштаб ваших идей.<br><span class="muted">Наша инфраструктура.</span>','Colocation.<br><span class="muted">Ваша техника — под нашей защитой.</span>');
s=s.replace('Выберите основу для следующего этапа<br>развития вашего бизнеса.','Размещение серверов и стоек — основа нашего предложения.<br>Облачные сервисы дополнят вашу инфраструктуру.');
s=s.replace('TAU CLOUD — казахстанский провайдер дата-центров и облачных решений. Мы соединяем физическую надёжность с гибкостью цифровых сервисов.','TAU CLOUD — казахстанский провайдер дата-центров. Наш основной фокус — Colocation: размещение вашего оборудования в подготовленной инфраструктуре с резервным питанием, охлаждением и контролем доступа.');
s=s.replace('Давайте создадим<br><em>вашу инфраструктуру.</em>','Разместите серверы.<br><em>Остальное — на нас.</em>');
s=s.replace('Расскажите о задаче. Подготовьте краткий бриф<br>для обсуждения с командой TAU CLOUD.','Укажите количество серверов или стоек и нужную мощность.<br>Подготовьте бриф для обсуждения размещения с TAU CLOUD.');
s=s.replace("panel.setAttribute('aria-labelledby',`tab-${s.id}`);","panel.setAttribute('aria-labelledby',`tab-${s.id}`);panel.dataset.solution=s.id;");
s=s.replace("selectService(0);","selectService(0);\ndocument.querySelectorAll('[data-colocation-cta]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('select').selectedIndex=0}));");
writeFileSync(path,s);
