import {readFileSync,writeFileSync} from 'node:fs';
let s=readFileSync('src/main.js','utf8');
s=s.replace("import {createCloudFinale} from './cloud-finale.js';", "import {initStory} from './story.js';\nimport {initMobileNav} from './mobile-nav.js';");
s=s.replace("const arrow=", "const mobileHeadlines=['Ваше оборудование.<br>Наша инфраструктура.','Надёжность внутри.','Мощность для вас.','Ваши идеи.<br>В облаке.'];\nconst arrow=");
s=s.replace('${c.title}</h1>', '<span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h1>');
s=s.replace('${c.title}</h2>', '<span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h2>');
s=s.replace('src="/media/exterior.jpeg" alt="Фасад', 'src="${matchMedia(\'(max-width:600px)\').matches?\'/media/mobile-opening.webp\':\'/media/exterior.jpeg\'}" alt="Фасад');
const a=s.indexOf('const menu=document.querySelector'),z=s.indexOf("document.querySelectorAll('[data-location]')",a);s=s.slice(0,a)+'initMobileNav();\n'+s.slice(z);
const start=s.indexOf('const story=document.querySelector');s=s.slice(0,start)+'initStory();\n';
writeFileSync('src/main.js',s);
