import {renderMobileStory} from './mobile-story.js';
import {chapters} from './story-content.js';
export {chapters} from './story-content.js';
export const services = [
 {id:'colocation',name:'Colocation',tag:'ВАШЕ ОБОРУДОВАНИЕ. НАША ИНФРАСТРУКТУРА.',text:'Разместите серверы в подготовленном дата-центре. Питание, охлаждение и физическая безопасность — на нашей стороне.',features:['Размещение серверов и стоек','Резервное электропитание','Круглосуточный контроль доступа'],number:'01'},
 {id:'iaas',name:'Облачная инфраструктура',tag:'РЕСУРСЫ, КОТОРЫЕ ПОДСТРАИВАЮТСЯ ПОД ВАС.',text:'Запускайте приложения и масштабируйте нагрузку без покупки физического оборудования. Выбирайте нужные вычислительные и сетевые ресурсы.',features:['IaaS · VPS · VDC VMware','Системы хранения данных','Виртуальный межсетевой экран VFW'],number:'02'},
 {id:'paas',name:'Платформы и сервисы',tag:'ОТ ИДЕИ ДО РАБОЧЕГО ПРИЛОЖЕНИЯ.',text:'Готовые среды для разработки, запуска приложений и совместной работы. Сосредоточьтесь на продукте, опираясь на нашу инфраструктуру.',features:['PaaS и среды приложений','Частное хранилище NextCloud','Помощь с миграцией и подключением'],number:'03'},
 {id:'build',name:'Строительство ЦОД',tag:'ВАША ИНФРАСТРУКТУРА С НУЛЯ.',text:'Обсудим создание дата-центра под задачи вашего бизнеса: от требований к мощности и размещению до инженерной инфраструктуры.',features:['Проработка требований к ЦОД','Инженерные системы','Подбор инфраструктурного решения'],number:'04'}
];
export const sites = [
 {city:'Астана',address:'ул. Алматы, 1/1А',status:'Готов к эксплуатации',active:true,power:'1,1',racks:'40',load:'25',note:'Действующая площадка'},
 {city:'Алматы',address:'СЭЗ «ПИТ «Алатау»',status:'Проектирование / строительство',active:false,power:'3',racks:'80',load:'30',note:'Проектная мощность · 1-я очередь: 2,8 МВт, 80 стоек'},
 {city:'Астана',address:'Жилой массив «Өндіріс»',status:'Проектирование / строительство',active:false,power:'3',racks:'80',load:'30',note:'Проектные характеристики'},
 {city:'Актау',power:'3',racks:'80'},
 {city:'Алматы',address:'Pioneer Edge',power:'150',powerUnit:'кВт',racks:'10'}
];

export const mobileHeadlines=['Ваши серверы.<br>Наша забота.','ДГУ и ИБП.','Серверные зоны.','Операторская.<br><em>Мониторинг 24/7.</em>','Команда инженеров.<br><em>Поддержка 24/7.</em>'];
export const storyMedia=Object.fromEntries(['desktop','mobile'].map(type=>[type,{
 base:'/media/energy-sequence'+(type==='mobile'?'-mobile':''),
 posters:Array.from({length:4},(_,i)=>i===0?'/media/energy-sequence'+(type==='mobile'?'-mobile':'')+'/0000.webp':'/media/energy-poster-'+i+(type==='mobile'?'-mobile':'')+'.webp')
}]));

// Editable page copy and semantic markup; interaction code lives in main.js.
export function renderPage(arrow){return `
<a class="skip" href="#solutions">Перейти к услугам</a>
<header><a class="brand" href="#" aria-label="TAU CLOUD — главная"><img src="/media/logo.png" alt="TAU CLOUD"></a><nav aria-label="Основная навигация"><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a></nav><a href="#contact" class="header-cta">Обсудить проект ${arrow}</a><button class="menu-button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Открыть меню"><svg class="menu-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12H20"/><path d="M4 12H20"/><path d="M4 12H20"/></svg></button><nav id="mobile-nav" hidden><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a><a href="#contact">Обсудить проект ↗</a></nav></header>
<main><section id="story" aria-label="История инфраструктуры TAU CLOUD">${renderMobileStory()}<div class="stage"><img id="poster" class="scene-media" ${matchMedia('(max-width:600px)').matches?'':`src="${storyMedia.desktop.posters[0]}"`} alt="Фасад дата-центра TAU CLOUD в Астане" fetchpriority="high"><canvas id="film" class="scene-media" aria-hidden="true"></canvas><div class="shade"></div><div class="stage-top"><span><i class="dot"></i> КАЗАХСТАН / АСТАНА</span><span class="stage-edition">ИНФРАСТРУКТУРА ВАШЕГО РОСТА</span></div><div class="chapters">${chapters.map((c,i)=>`<article class="chapter ${i===0?'active':''}" data-chapter="${i}" ${i?'inert':''}><p class="eyebrow">${c.kicker}</p><h1 ${i?'hidden':''}><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h1>${i?`<h2><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h2>`:''}<p class="hero-description">${c.text}</p><a class="button primary" href="${i<3?'#contact':'#solutions'}" ${i<3?'data-colocation-cta':''}>${i<3?'Обсудить размещение':'Найти своё решение'} ${arrow}</a></article>`).join('')}</div><div class="stage-bottom"><div class="scroll-note"><span class="scroll-icon">↓</span><span>ПРОКРУТИТЕ,<br>ЧТОБЫ ЗАГЛЯНУТЬ ВНУТРЬ</span></div><a href="#solutions" class="skip-story">Пропустить историю ↘</a><span class="chapter-counter">01 <span>/ 05</span></span></div><div class="chapter-nav" aria-label="Главы истории">${chapters.map((c,i)=>`<button data-jump="${i}" class="${i===0?'current':''}" aria-label="Глава ${i+1}: ${c.label}"><span>0${i+1}</span><span>${c.label}</span><i></i></button>`).join('')}</div></div></section>
<section id="about" class="section about"><div class="section-label"><span>01 / О КОМПАНИИ</span><span>ОПОРА ДЛЯ ЦИФРОВОГО БИЗНЕСА</span></div><div class="about-grid"><h2>За каждым облаком — <span class="about-title-accent">реальная инфраструктура.</span></h2><div class="about-copy"><p class="about-lead">Размещаем ваше оборудование<br class="about-desktop-break"> в дата-центрах Казахстана.</p><p>TAU CLOUD берёт на себя питание, охлаждение и контроль доступа. Вы получаете подготовленную инфраструктуру для работы ваших серверов — это услуга Colocation.</p><p>Помогаем бизнесу расти: от размещения одного сервера до облачной среды и строительства собственного дата-центра.</p><a class="text-link about-link" href="#locations">Выбрать дата-центр ${arrow}</a></div></div><div class="metrics"><div><strong>1,1 <small>МВт</small></strong><span>Подводимая мощность в Астане</span></div><div><strong>40 <small>стоек</small></strong><span>На площадке ул. Алматы, 1/1А</span></div><div><strong>25 <small>кВт</small></strong><span>До 25 кВт на стойку</span></div><div><strong>24<span class="cyan">/</span>7</strong><span>Физический контроль доступа</span></div></div></section>
<section id="solutions" class="section solutions"><div class="section-label"><span>02 / РЕШЕНИЯ</span><span>ОТ ОДНОЙ СТОЙКИ ДО СОБСТВЕННОГО ЦОД</span></div><div class="section-heading"><h2>Инфраструктура для ваших задач.</h2><p>Размещайте серверы, запускайте облачные сервисы<br> или создавайте собственный дата-центр.</p></div><div class="service-tabs" role="tablist" aria-label="Инфраструктурные решения">${services.map((s,i)=>`<button role="tab" id="tab-${s.id}" aria-controls="service-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-service="${i}"><span>${s.number}</span>${s.id==='colocation'?'Размещение серверов':s.id==='iaas'?'Облако / IaaS':s.id==='paas'?'Платформы / PaaS':s.name}</button>`).join('')}</div><div id="service-panel" role="tabpanel" aria-labelledby="tab-colocation" tabindex="0"></div></section>
<section class="reliability"><div class="reliability-background" aria-hidden="true"><canvas></canvas></div><div class="reliability-content"><p class="eyebrow">ПРОДУМАНО НА КАЖДОМ УРОВНЕ</p><h2>Спокойствие это тоже технология.</h2><div class="reliability-grid"><div><span>01</span><h3>Резервирование</h3><p>Питание и охлаждение для непрерывной работы оборудования.</p></div><div><span>02</span><h3>Безопасность</h3><p>Физический контроль доступа и защита облачного периметра.</p></div><div><span>03</span><h3>Специалисты рядом</h3><p>Инженерная поддержка при миграции, подключении и обслуживании.</p></div></div></div></section>
<section id="locations" class="section locations"><div class="section-label"><span>03 / ГЕОГРАФИЯ</span><span>СОЗДАЁМ ЦИФРОВУЮ ОСНОВУ КАЗАХСТАНА</span></div><div class="section-heading"><h2>Ближе к вашему бизнесу.</h2><p>Астана · Алматы · Актау</p></div><div id="location-carousel"></div><p class="source-note">Характеристики приведены по материалам компании. Проекты развиваются по требованиям уровня Tier III; наличие сертификата Uptime Institute отдельно не заявляется.</p></section>
<section id="contact" class="section contact"><div><p class="eyebrow">СЛЕДУЮЩИЙ ШАГ — ВАШ</p><h2>Обсудим ваш проект.</h2><p class="contact-intro">Укажите количество серверов или стоек и нужную мощность.<br>Подготовьте бриф для обсуждения размещения с TAU CLOUD.</p><div class="contact-actions"><a class="button primary" href="tel:+77172251344">Позвонить</a><a class="button outline" href="mailto:info@taucloud.kz">Написать</a></div><p class="contact-address">+7 7172 251344 · info@taucloud.kz</p><a class="text-link" href="https://taucloud.kz/" target="_blank" rel="noopener">Официальный сайт TAU CLOUD ${arrow}</a></div><form id="brief"><h3>Подготовить бриф</h3><p class="brief-intro">Дополнительно: сохраните описание проекта в файл. Скачивание не отправляет заявку.</p><label>Ваше имя (обязательно)<input name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="100"></label><label>Рабочий email (обязательно)<input name="email" type="email" autocomplete="email" placeholder="name@company.kz" required maxlength="150"></label><label>Что вас интересует<select name="service">${services.map(s=>`<option>${s.name}</option>`).join('')}</select></label><label>О проекте<textarea name="message" placeholder="Задача, мощность, сроки или вопросы" rows="3" maxlength="3000"></textarea></label><button class="button primary" type="submit">Скачать бриф проекта <span>↓</span></button><p class="form-note">Бриф скачивается на ваше устройство. Данные никуда не отправляются. Передайте файл команде через официальный канал связи.</p><p id="form-status" role="status"></p></form></section></main>
<footer><a class="brand" href="#"><img src="/media/logo.png" alt="TAU CLOUD"></a><p>Надёжная инфраструктура.<br>Новые возможности.</p><div><span>ТОО «TAU CLOUD» · БИН 151040007742</span><span>Юридический адрес: Астана, ул. Сығанақ, 29</span></div><a href="#">Наверх ↑</a><div class="footer-bottom"><span>© ${new Date().getFullYear()} TAU CLOUD</span><span>СОЗДАНО ДЛЯ РОСТА</span><a href="/style-tile.html">Дизайн-система ↗</a></div></footer>`;}

export const serviceImages=[
 {src:'/media/capsule-angle.webp',small:'/media/capsule-angle-small.webp',width:1672,alt:'Серверные капсулы TAU CLOUD'},
 {src:'/media/cloud-infrastructure-blue.webp',small:'/media/cloud-infrastructure-blue-small.webp',width:1672,alt:'Визуализация облачной инфраструктуры: облако и связанные серверы'},
 {src:'/media/platform-services.webp',small:'/media/platform-services-small.webp',width:1672,alt:'Облачные платформы и сервисы: светящееся облако на электронной плате'},
 {src:'/media/datacenter-construction.webp',small:'/media/datacenter-construction-small.webp',width:1672,alt:'Визуализация здания дата-центра TAU CLOUD в Алматы'}
];
