import {renderMobileStory} from './mobile-story.js';
import {chapters} from './story-content.js';
export {chapters} from './story-content.js';
export const services = [
 {id:'colocation',name:'Colocation',tag:'ВАШЕ ОБОРУДОВАНИЕ. НАША ИНФРАСТРУКТУРА.',text:'Разместите серверы в подготовленном дата-центре. Питание, охлаждение и физическая безопасность — на нашей стороне.',features:['Размещение серверов и стоек','Резервное электропитание','Круглосуточный контроль доступа'],number:'01'},
 {id:'iaas',name:'Облачная инфраструктура',tag:'РЕСУРСЫ, КОТОРЫЕ ПОДСТРАИВАЮТСЯ ПОД ВАС.',text:'Запускайте приложения и масштабируйте нагрузку без покупки физического оборудования. Выбирайте нужные вычислительные и сетевые ресурсы.',features:['IaaS · VPS · VDC VMware','Системы хранения данных','Виртуальный межсетевой экран VFW'],number:'02'},
 {id:'paas',name:'Платформы и сервисы',tag:'ОТ ИДЕИ ДО РАБОЧЕГО ПРИЛОЖЕНИЯ.',text:'Готовые среды для разработки, запуска приложений и совместной работы. Сосредоточьтесь на продукте, опираясь на нашу инфраструктуру.',features:['PaaS и среды приложений','Частное хранилище NextCloud','Помощь с миграцией и подключением'],number:'03'},
 {id:'build',name:'Строительство ЦОД',tag:'ВАША ИНФРАСТРУКТУРА С НУЛЯ.',text:'Обсудим создание дата-центра под задачи вашего бизнеса: от требований к мощности и размещению до инженерной инфраструктуры.',features:['Проработка требований к ЦОД','Инженерные системы','Подбор инфраструктурного решения'],number:'04'}
];
export const sites = [
 {city:'Астана',address:'ул. Алматы, 1/1А',status:'Готов к эксплуатации',active:true,power:'1,1',racks:'40',load:'25',note:'Действующая площадка'},
 {city:'Алматы',address:'СЭЗ «ПИТ «Алатау»',status:'Проектирование / строительство',active:false,power:'3',racks:'80',load:'30',note:'Проектная мощность · 1-я очередь: 3 МВт, 80 стоек\n2-я очередь: 3 МВт, 80 стоек',project:{
  title:'',cardTitle:'',subtitle:'СЭЗ «ПИТ «Алатау» · Алматы',
  summary:'Облачная инфраструктура для корпоративного сектора Центральной Азии.',
  paragraphs:[
   'Технологический корпус уровня Tier III в специальной экономической зоне ПИТ «Алатау» — облачная инфраструктура для корпоративного сектора Центральной Азии.',
   'Площадка в Алматы — вторая точка роста Tau Cloud. Проект прошёл стадию технико-экономического обоснования и находится на стадии эскизного проекта; следующий шаг — рабочая документация и строительство.',
   'Дизайн-концепция фасада — «PURE TECH»: чистота, технологии и надёжность. Корпус объединяет четыре аппаратных зала, помещение ИБП/ВРУ и полноценную офисную зону — по той же модели отказоустойчивости, что и в Астане.'
  ],
  sections:[
   {title:'Преимущества площадки',text:'Аппаратные залы, электрощитовое оборудование и офисная зона спроектированы как единый комплекс, а не просто серверная. Светлые фасадные панели, графитовые вертикальные ламели и фирменная голубая подсветка создают визуальный язык «PURE TECH». Отдельные технические помещения предусмотрены для вентиляции, электропитания и пожаротушения, а переговорные, кабинеты и зоны отдыха делают площадку комфортной для сотрудников и клиентов.'},
   {title:'Миссия компании',text:'Tau Cloud развивает надёжную, безопасную и инновационную цифровую инфраструктуру для бизнеса, государственных организаций и технологических компаний Казахстана и Центральной Азии — от хранения и обработки данных до поддержки искусственного интеллекта и облачных технологий. Каждая новая площадка, включая Алматы, поддерживает безопасность и непрерывность ИТ-сервисов и цифровой суверенитет Казахстана.'}
  ],
  images:[
   {src:'/media/alatau-aerial.webp',alt:'Визуализация технологического корпуса Tau Cloud в СЭЗ ПИТ «Алатау» с высоты',caption:'Общий вид площадки в СЭЗ ПИТ «Алатау»',width:1052,height:697},
   {src:'/media/alatau-exterior.webp',alt:'Визуализация технологического корпуса Tau Cloud в СЭЗ ПИТ «Алатау»',caption:'Технологический корпус Tier III',width:1142,height:593},
   {src:'/media/alatau-facade.webp',alt:'Вечерняя визуализация фасада Tau Cloud в Алматы',caption:'Фасад в концепции PURE TECH',width:1146,height:800},
   {src:'/media/alatau-concept-board.webp',alt:'Концептуальный лист фасада технологического корпуса Tau Cloud',caption:'Материалы и архитектурная концепция фасада',width:1320,height:997}
  ]
 }},
 {city:'Астана',address:'Жилой массив «Өндіріс»',status:'Проектирование / строительство',active:false,power:'3',racks:'80',load:'30'},
 {city:'Актау',status:'Проектирование / строительство',power:'3',racks:'80'},
 {city:'Алматы',address:'г.Алматы, пр.Достык 134',status:'Проектирование / строительство',power:'150',powerUnit:'кВт',racks:'10',project:{
  title:'Pioneer Edge',subtitle:'Алматы',summary:'Проектируемая edge-площадка Tau Cloud в Алматы.',paragraphs:[],
  images:[
   {src:'/media/pioneer-edge-front.webp',alt:'Визуализация модульной edge-площадки Tau Cloud Pioneer Edge',caption:'Модульная edge-площадка Pioneer Edge',width:1280,height:768},
   {src:'/media/pioneer-edge-aerial.webp',alt:'Визуализация Pioneer Edge Tau Cloud с высоты',caption:'Pioneer Edge: вид сверху',width:1280,height:768}
  ]
 }},
 {city:'Астана',address:'БЦ «Асылтау»',status:'Начата подготовка площадей',project:{
  title:'Мини Meta Computing Center',subtitle:'с коворкинг-пространством',
  summary:'Высокопроизводительная вычислительная инфраструктура и коворкинг для IT-команд, разработчиков и технологических компаний.',
  paragraphs:[
   'В бизнес-центре Асылтау (г. Астана) начаты работы по подготовке площадей для размещения мини Meta Computing Center с коворкинг-пространством.',
   'Проект предусматривает создание современного вычислительного центра, интегрированного с открытой рабочей средой для IT-команд, разработчиков и технологических компаний.',
   'Концепция объединяет высокопроизводительную вычислительную инфраструктуру и комфортное офисное пространство, создавая единую экосистему для разработки, тестирования и эксплуатации цифровых сервисов.'
  ],
  images:[
   {src:'/media/asyltau-coworking.png',alt:'Рабочие места и зона отдыха рядом с серверной за стеклянной перегородкой',caption:'Вычислительная инфраструктура и открытая рабочая среда',width:841,height:555},
   {src:'/media/asyltau-meta-center.jpeg',alt:'Концепция мини Meta Computing Center с коворкинг-пространством в бизнес-центре Асылтау, Астана',caption:'Meta Computing Center · БЦ «Асылтау», Астана',width:1536,height:1024}
  ]
 }}
];

export const mobileHeadlines=['Ваши серверы.<br>Наша забота.','ДГУ и ИБП.','Серверные зоны.','Операторская.<br><em>Мониторинг 24/7.</em>','Команда инженеров.<br><em>Поддержка 24/7.</em>'];
export const storyMedia=Object.fromEntries(['desktop','mobile'].map(type=>[type,{
 base:'/media/energy-sequence'+(type==='mobile'?'-mobile':''),
 posters:Array.from({length:4},(_,i)=>i===0?'/media/energy-sequence'+(type==='mobile'?'-mobile':'')+'/0000.webp':'/media/energy-poster-'+i+(type==='mobile'?'-mobile':'')+'.webp')
}]));

// Editable page copy and semantic markup; interaction code lives in main.js.
export function renderPage(arrow){return `
<a class="skip" href="#solutions">Перейти к услугам</a>
<header><a class="brand" href="#" aria-label="TAU CLOUD — главная"><img src="/media/logo.png" alt="TAU CLOUD"></a><nav aria-label="Основная навигация"><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a></nav><a href="#contact" class="header-cta">Обсудить проект ${arrow}</a><button class="menu-button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Открыть меню"><svg class="menu-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12H20"/><path d="M4 12H20"/><path d="M4 12H20"/></svg></button><nav id="mobile-nav" hidden><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a><a href="#contact">Обсудить проект ↗</a></nav></header>
<main><section id="story" aria-label="История инфраструктуры TAU CLOUD">${renderMobileStory()}<div class="stage"><img id="poster" class="scene-media" ${matchMedia('(max-width:600px)').matches?'':`src="${storyMedia.desktop.posters[0]}"`} alt="Фасад дата-центра TAU CLOUD в Астане" fetchpriority="high"><canvas id="film" class="scene-media" aria-hidden="true"></canvas><div class="shade"></div><div class="stage-top"><span><i class="dot"></i> КАЗАХСТАН / АСТАНА</span><span class="stage-edition">ИНФРАСТРУКТУРА ВАШЕГО РОСТА</span></div><div class="chapters">${chapters.map((c,i)=>`<article class="chapter ${i===0?'active':''}" data-chapter="${i}" ${i?'inert':''}><p class="eyebrow">${c.kicker}</p><h1 ${i?'hidden':''}><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h1>${i?`<h2><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h2>`:''}<p class="hero-description">${c.text}</p><a class="button primary" href="${i<3?'#contact':'#solutions'}" ${i<3?'data-colocation-cta':''}>${i<3?'Обсудить размещение':'Найти своё решение'} ${arrow}</a></article>`).join('')}</div><div class="stage-bottom"><div class="scroll-note"><span class="scroll-icon">↓</span><span>ПРОКРУТИТЕ,<br>ЧТОБЫ ЗАГЛЯНУТЬ ВНУТРЬ</span></div><a href="#solutions" class="skip-story">Пропустить историю ↘</a><span class="chapter-counter">01 <span>/ 05</span></span></div><div class="chapter-nav" aria-label="Главы истории">${chapters.map((c,i)=>`<button data-jump="${i}" class="${i===0?'current':''}" aria-label="Глава ${i+1}: ${c.label}"><span>0${i+1}</span><span>${c.label}</span><i></i></button>`).join('')}</div></div></section>
<section id="about" class="section about"><div class="section-label"><span>01 / О КОМПАНИИ</span><span>ИНФРАСТРУКТУРА ДЛЯ БОЛЬШИХ ЗАДАЧ</span></div><div class="about-grid"><h2><span class="about-title-accent"><span class="about-title-highlight">Мощность</span> для больших задач.</span></h2><div class="about-copy"><p>TAU CLOUD — казахстанская технологическая компания, создающая инфраструктуру для хранения, обработки и передачи данных. Мы развиваем дата-центры и облачные решения, объединяя собственные площадки, инженерную экспертизу и компетенции в эксплуатации критически важных систем.</p><p>Наша сила — в комплексном подходе: от проектирования и строительства дата-центров до размещения серверов и управления вычислительными ресурсами. Электроснабжение, охлаждение, связь и безопасность формируют единую инфраструктуру, рассчитанную на высокие нагрузки и непрерывную работу.</p><p>Мы расширяем мощности и географию присутствия в Казахстане, создавая основу для корпоративных IT-систем, цифровых платформ и ресурсоёмких вычислений.</p><p class="about-closing"><strong>Собственная инфраструктура. Сильная инженерная команда.<br>Масштаб для роста.</strong></p><a class="text-link about-link" href="#locations">Выбрать дата-центр ${arrow}</a></div></div></section>
<section id="solutions" class="section solutions"><div class="section-label"><span>02 / РЕШЕНИЯ</span><span>ОТ ОДНОЙ СТОЙКИ ДО СОБСТВЕННОГО ЦОД</span></div><div class="section-heading"><h2>Инфраструктура для ваших задач.</h2><p>Размещайте серверы, запускайте облачные сервисы<br> или создавайте собственный дата-центр.</p></div><div class="service-tabs" role="tablist" aria-label="Инфраструктурные решения">${services.map((s,i)=>`<button role="tab" id="tab-${s.id}" aria-controls="service-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-service="${i}"><span>${s.number}</span>${s.id==='colocation'?'Размещение серверов':s.id==='iaas'?'Облако / IaaS':s.id==='paas'?'Платформы / PaaS':s.name}</button>`).join('')}</div><div id="service-panel" role="tabpanel" aria-labelledby="tab-colocation" tabindex="0"></div></section>
<section class="reliability" aria-labelledby="reliability-title"><div class="reliability-background" aria-hidden="true"><canvas></canvas></div><div class="reliability-content"><p class="eyebrow">НАДЁЖНОСТЬ TAU CLOUD</p><h2 id="reliability-title">Всё для стабильной<br>работы ваших сервисов.</h2><div class="reliability-grid"><div><svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-server reliability-icon" aria-hidden="true"><rect width="20" height="8" x="2" y="2" rx="2" ry="2"></rect><rect width="20" height="8" x="2" y="14" rx="2" ry="2"></rect><line x1="6" x2="6.01" y1="6" y2="6"></line><line x1="6" x2="6.01" y1="18" y2="18"></line></svg><h3>Резерв на случай сбоев</h3><p>Резервируем питание и охлаждение. Независимые каналы связи снижают риск потери соединения.</p></div><div><svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-check reliability-icon" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg><h3>Доступ под контролем</h3><p>Охраняем площадку круглосуточно. Ограничиваем доступ в серверные помещения.</p></div><div><svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-headset reliability-icon" aria-hidden="true"><path d="M3 11h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-5Zm0 0a9 9 0 1 1 18 0m0 0v5a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3Z"></path><path d="M21 16v2a4 4 0 0 1-4 4h-5"></path></svg><h3>Инженеры на связи</h3><p>Помогаем с миграцией и подключением. Сопровождаем инфраструктуру после запуска.</p></div></div></div></section>
<section id="locations" class="section locations"><div class="section-label"><span>03 / ГЕОГРАФИЯ</span><span>СОЗДАЁМ ЦИФРОВУЮ ОСНОВУ КАЗАХСТАНА</span></div><div class="section-heading"><h2>Ближе к вашему бизнесу.</h2><p>Астана · Алматы · Актау</p></div><div id="location-carousel"></div></section>
<section id="contact" class="section contact"><div><p class="eyebrow">СЛЕДУЮЩИЙ ШАГ — ВАШ</p><h2>Обсудим ваш проект.</h2><p class="contact-intro">Укажите количество серверов или стоек и нужную мощность.<br>Подготовьте бриф для обсуждения размещения с TAU CLOUD.</p><div class="contact-guide"><p class="contact-guide-label">КАК МЫ РАБОТАЕМ</p><ol class="contact-steps"><li><span class="contact-step-number" aria-hidden="true">01</span><div><h3>Ваша задача</h3><p>Серверы, облако или новый ЦОД — с чего начнём?</p></div></li><li><span class="contact-step-number" aria-hidden="true">02</span><div><h3>Ключевые детали</h3><p>Уточним ресурсы, нагрузку и сроки запуска.</p></div></li><li><span class="contact-step-number" aria-hidden="true">03</span><div><h3>Подходящее решение</h3><p>Согласуем конфигурацию для расчёта стоимости.</p></div></li></ol><div class="contact-help"><span aria-hidden="true">↗</span><p><strong>Нет готового ТЗ?</strong>Опишите идею. Детали обсудим вместе.</p></div></div></div><form id="brief" aria-label="Заявка на проект"><div class="brief-honeypot" aria-hidden="true"><label>Ваш сайт<input name="website" tabindex="-1" autocomplete="off"></label></div><h3>Заявка на проект</h3><p class="brief-intro">Опишите задачу и оставьте номер для связи.</p><label>Название компании / проекта<input name="company" autocomplete="organization" maxlength="150" placeholder="Название компании"></label><label>БИН<input name="bin" inputmode="numeric" pattern="[0-9]{12}" minlength="12" maxlength="12" placeholder="12 цифр"></label><label>Ваше имя *<input name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="100"></label><label>Телефон<input name="phone" type="tel" autocomplete="tel" maxlength="40" pattern="[+0-9\s().\-]{7,40}" placeholder="+7 (___) ___-__-__"></label><label>Желаемая дата запуска<input name="launch" type="date"></label><label>Услуга<select name="service">${services.map(s=>`<option>${s.name}</option>`).join('')}</select></label><label>Задача<textarea name="message" placeholder="Что нужно разместить или запустить? Укажите объём и сроки." rows="5" maxlength="3000"></textarea></label><button class="button primary" type="submit">Отправить заявку <span aria-hidden="true">↗</span></button><p id="form-status" role="status"></p></form></section></main>
<footer><a class="brand" href="#"><img src="/media/logo.png" alt="TAU CLOUD"></a><p>Надёжная инфраструктура.<br>Новые возможности.</p><div class="footer-legal"><span>ТОО «TAU CLOUD» · БИН 151040007742</span><span>Юридический адрес: Астана, ул. Сығанақ, 29</span></div><div class="footer-contacts"><span>ТЕЛЕФОН</span><a href="tel:+77172251344">+7 7172 251 344</a><a href="tel:+77087777818">+7 708 777 7818</a></div><a href="#">Наверх ↑</a><div class="footer-bottom"><span>© ${new Date().getFullYear()} TAU CLOUD</span><span>СОЗДАНО ДЛЯ РОСТА</span><a href="/style-tile.html">Дизайн-система ↗</a></div></footer>`;}

export const serviceImages=[
 {src:'/media/capsule-angle.webp',small:'/media/capsule-angle-small.webp',width:1672,alt:'Серверные капсулы TAU CLOUD'},
 {src:'/media/cloud-infrastructure-blue.webp',small:'/media/cloud-infrastructure-blue-small.webp',width:1672,alt:'Визуализация облачной инфраструктуры: облако и связанные серверы'},
 {src:'/media/platform-services.webp',small:'/media/platform-services-small.webp',width:1672,alt:'Облачные платформы и сервисы: светящееся облако на электронной плате'},
 {src:'/media/datacenter-build-photo.webp',small:'/media/datacenter-build-photo-small.webp',width:1104,alt:'Строительство дата-центра: монтаж здания и инженерных систем'}
];

