import {initSmoothScroll} from './smooth-scroll.js';
import {chapters,services,sites} from './content.js';
import {initStory} from './story.js';
import {initMobileNav} from './mobile-nav.js';
const mobileHeadlines=['Ваше оборудование.<br>Наша инфраструктура.','Надёжность внутри.','Мощность для вас.','Ваши идеи.<br>В облаке.'];
const arrow='<span aria-hidden="true">↗</span>';
document.querySelector('#app').innerHTML=`
<a class="skip" href="#solutions">Перейти к услугам</a>
<header><a class="brand" href="#" aria-label="TAU CLOUD — главная"><img src="/media/logo.png" alt="TAU CLOUD"></a><nav aria-label="Основная навигация"><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a></nav><a href="#contact" class="header-cta">Обсудить проект ${arrow}</a><button class="menu-button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Открыть меню">☰</button><nav id="mobile-nav" hidden><a href="#about">О компании</a><a href="#solutions">Решения</a><a href="#locations">Дата-центры</a><a href="#contact">Обсудить проект ↗</a></nav></header>
<main><section id="story" aria-label="История инфраструктуры TAU CLOUD"><div class="stage"><img id="poster" class="scene-media" src="${matchMedia('(max-width:600px)').matches?'/media/mobile-opening.webp':'/media/exterior.jpeg'}" alt="Фасад дата-центра TAU CLOUD в Астане" fetchpriority="high"><canvas id="film" class="scene-media" aria-hidden="true"></canvas><div class="shade"></div><div class="stage-top"><span><i class="dot"></i> КАЗАХСТАН / АСТАНА</span><span class="stage-edition">ИНФРАСТРУКТУРА ВАШЕГО РОСТА</span></div><div class="chapters">${chapters.map((c,i)=>`<article class="chapter ${i===0?'active':''}" data-chapter="${i}" ${i?'inert':''}><p class="eyebrow">${c.kicker}</p><h1 ${i?'hidden':''}><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h1>${i?`<h2><span class="desktop-copy">${c.title}</span><span class="mobile-copy">${mobileHeadlines[i]}</span></h2>`:''}<p class="hero-description">${c.text}</p><a class="button primary" href="${i<3?'#contact':'#solutions'}" ${i<3?'data-colocation-cta':''}>${i<3?'Обсудить размещение':'Найти своё решение'} ${arrow}</a></article>`).join('')}</div><div class="stage-bottom"><div class="scroll-note"><span class="scroll-icon">↓</span><span>ПРОКРУТИТЕ,<br>ЧТОБЫ ЗАГЛЯНУТЬ ВНУТРЬ</span></div><a href="#solutions" class="skip-story">Пропустить историю ↘</a><span class="chapter-counter">01 <span>/ 04</span></span></div><div class="chapter-nav" aria-label="Главы истории">${chapters.map((c,i)=>`<button data-jump="${i}" class="${i===0?'current':''}" aria-label="Глава ${i+1}: ${c.label}"><span>0${i+1}</span><span>${c.label}</span><i></i></button>`).join('')}</div></div></section>
<section id="about" class="section about"><div class="section-label"><span>01 / О КОМПАНИИ</span><span>ОПОРА ДЛЯ ЦИФРОВОГО БИЗНЕСА</span></div><div class="about-grid"><h2>За каждым облаком —<br><span class="muted">реальная инфраструктура.</span></h2><div><p>TAU CLOUD — казахстанский провайдер дата-центров. Наш основной фокус — Colocation: размещение вашего оборудования в подготовленной инфраструктуре с резервным питанием, охлаждением и контролем доступа.</p><p class="muted">От размещения одного сервера до собственной облачной среды и строительства ЦОД. Помогаем бизнесу запускать, защищать и развивать ИТ-системы.</p><a class="text-link" href="#locations">Посмотреть наши площадки ${arrow}</a></div></div><div class="metrics"><div><strong>1,1 <small>МВт</small></strong><span>Подводимая мощность в Астане</span></div><div><strong>40 <small>стоек</small></strong><span>На площадке ул. Алматы, 1/1А</span></div><div><strong>25 <small>кВт</small></strong><span>До 25 кВт на стойку</span></div><div><strong>24<span class="cyan">/</span>7</strong><span>Физический контроль доступа</span></div></div></section>
<section id="solutions" class="section solutions"><div class="section-label"><span>02 / РЕШЕНИЯ</span><span>ОТ ОДНОЙ СТОЙКИ ДО СОБСТВЕННОГО ЦОД</span></div><div class="section-heading"><h2>Colocation.<br><span class="muted">Ваша техника — под нашей защитой.</span></h2><p>Размещение серверов и стоек — основа нашего предложения.<br> Облачные сервисы дополнят вашу инфраструктуру.</p></div><div class="service-tabs" role="tablist" aria-label="Инфраструктурные решения">${services.map((s,i)=>`<button role="tab" id="tab-${s.id}" aria-controls="service-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-service="${i}"><span>${s.number}</span>${s.id==='iaas'?'IaaS / Облако':s.id==='paas'?'PaaS / Сервисы':s.name}</button>`).join('')}</div><div class="catalog-navigation" aria-label="Переключение решений"><button type="button" data-service-direction="-1" aria-label="Предыдущее решение">←</button><button type="button" data-service-direction="1" aria-label="Следующее решение">→</button></div><div id="service-panel" role="tabpanel" aria-labelledby="tab-colocation" tabindex="0"></div></section>
<section class="reliability"><img src="/media/hall.jpg" loading="lazy" alt="Серверные капсулы TAU CLOUD"><div class="reliability-content"><p class="eyebrow">ПРОДУМАНО НА КАЖДОМ УРОВНЕ</p><h2>Спокойствие —<br>тоже технология.</h2><div class="reliability-grid"><div><span>01</span><h3>Резервирование</h3><p>Питание и охлаждение для непрерывной работы оборудования.</p></div><div><span>02</span><h3>Безопасность</h3><p>Физический контроль доступа и защита облачного периметра.</p></div><div><span>03</span><h3>Люди рядом</h3><p>Инженерная поддержка при миграции, подключении и обслуживании.</p></div></div></div></section>
<section id="locations" class="section locations"><div class="section-label"><span>03 / ГЕОГРАФИЯ</span><span>СОЗДАЁМ ЦИФРОВУЮ ОСНОВУ КАЗАХСТАНА</span></div><div class="section-heading"><h2>Ближе к вашему бизнесу.</h2><p>Одна действующая площадка.<br>Два проекта развития.</p></div><div class="location-grid">${sites.map((s,i)=>`<article class="location"><div class="location-top"><span>0${i+1} / KZ</span><span class="status ${s.active?'live':''}"><i></i>${s.status}</span></div><h3>${s.city}</h3><p class="address">${s.address}</p><div class="location-stats"><div><strong>${s.power}<small> МВт</small></strong><span>${s.active?'Подводимая':'Проектная'} мощность</span></div><div><strong>${s.racks}</strong><span>${i===1?'Стоек в 1-й очереди':'Серверных стоек'}</span></div></div><p class="location-note">${s.note}</p><a href="#contact" data-location="${i}">Обсудить размещение ${arrow}</a></article>`).join('')}</div><p class="source-note">Характеристики приведены по материалам компании. Проекты развиваются по требованиям уровня Tier III; наличие сертификата Uptime Institute отдельно не заявляется.</p></section>
<section id="contact" class="section contact"><div><p class="eyebrow">СЛЕДУЮЩИЙ ШАГ — ВАШ</p><h2>Разместите серверы.<br><em>Остальное — на нас.</em></h2><p>Укажите количество серверов или стоек и нужную мощность.<br>Подготовьте бриф для обсуждения размещения с TAU CLOUD.</p><a class="text-link" href="https://taucloud.kz/" target="_blank" rel="noopener">Официальный сайт TAU CLOUD ${arrow}</a></div><form id="brief"><label>Ваше имя<input name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="100"></label><label>Рабочий email<input name="email" type="email" autocomplete="email" placeholder="name@company.kz" required maxlength="150"></label><label>Что вас интересует<select name="service">${services.map(s=>`<option>${s.name}</option>`).join('')}</select></label><label>О проекте<textarea name="message" placeholder="Задача, мощность, сроки или вопросы" rows="3" maxlength="3000"></textarea></label><button class="button primary" type="submit">Скачать бриф проекта <span>↓</span></button><p class="form-note">Бриф скачивается на ваше устройство. Данные никуда не отправляются. Передайте файл команде через официальный канал связи.</p><p id="form-status" role="status"></p></form></section></main>
<footer><a class="brand" href="#"><img src="/media/logo.png" alt="TAU CLOUD"></a><p>Надёжная инфраструктура.<br>Новые возможности.</p><div><span>ТОО «TAU CLOUD» · БИН 151040007742</span><span>Юридический адрес: Астана, ул. Сығанақ, 29</span></div><a href="#">Наверх ↑</a><div class="footer-bottom"><span>© ${new Date().getFullYear()} TAU CLOUD</span><span>СОЗДАНО ДЛЯ РОСТА</span><a href="/style-tile.html">Дизайн-система ↗</a></div></footer>`;
let currentService=0;
function selectService(i,focus=false){currentService=i;const s=services[i];document.querySelectorAll('[data-service]').forEach((b,j)=>{b.setAttribute('aria-selected',j===i);b.tabIndex=j===i?0:-1;if(j===i&&focus)b.focus()});const panel=document.querySelector('#service-panel');panel.setAttribute('aria-labelledby',`tab-${s.id}`);panel.dataset.solution=s.id;panel.innerHTML=`<div class="service-copy"><p class="eyebrow">${s.tag}</p><h3>${s.name}</h3><p>${s.text}</p><ul>${s.features.map(f=>`<li><span>↗</span>${f}</li>`).join('')}</ul><a href="#contact" class="button outline" id="choose-service">Обсудить решение ${arrow}</a></div><div class="service-image"><img src="/media/${i===3?'exterior.jpeg':'capsule.jpg'}" loading="lazy" alt="${i===3?'Здание дата-центра':'Серверная капсула'} TAU CLOUD"><div><span>TAU CLOUD / ${s.number}</span><span>ИНФРАСТРУКТУРА БЕЗ ЛИШНЕЙ СЛОЖНОСТИ</span></div></div>`;document.querySelector('#choose-service').onclick=()=>document.querySelector('select').selectedIndex=i;}
selectService(0);
document.querySelectorAll('[data-colocation-cta]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('select').selectedIndex=0}));
document.querySelectorAll('[data-service]').forEach(b=>{b.onclick=()=>selectService(+b.dataset.service);b.onkeydown=e=>{let n=currentService;if(e.key==='ArrowRight')n=(n+1)%4;else if(e.key==='ArrowLeft')n=(n+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();selectService(n,true)}});
document.querySelectorAll('[data-service-direction]').forEach(button=>button.onclick=()=>selectService((currentService+Number(button.dataset.serviceDirection)+services.length)%services.length));
initSmoothScroll();
initMobileNav();
document.querySelectorAll('[data-location]').forEach(a=>a.onclick=()=>{document.querySelector('select').selectedIndex=0;document.querySelector('textarea').value=`Интересует площадка: ${sites[+a.dataset.location].city}, ${sites[+a.dataset.location].address}. `});
document.querySelector('#brief').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const body=`БРИФ ПРОЕКТА TAU CLOUD\n\nИмя: ${d.get('name')}\nEmail: ${d.get('email')}\nРешение: ${d.get('service')}\n\nО проекте:\n${d.get('message')||'Не указано'}\n\nБриф создан локально и не отправлен. Официальный сайт: https://taucloud.kz/`;const url=URL.createObjectURL(new Blob(['\ufeff',body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TAU-CLOUD-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#form-status').textContent='Бриф подготовлен к скачиванию. Передайте его команде TAU CLOUD.';};
initStory();

import './style.css';
import './mobile.css';
