import {createFrameSource} from './frame-source.js';
import {scrollPageTo} from './smooth-scroll.js';
import {storyMedia} from './content.js';
import {desktopMoment} from './story-timeline.js';

export function initStory(){
 const story=document.querySelector('#story'),stage=story.querySelector('.stage'),canvas=story.querySelector('#film'),poster=story.querySelector('#poster'),ctx=canvas.getContext('2d');
 const mobile=matchMedia('(max-width:600px)'),reduce=matchMedia('(prefers-reduced-motion:reduce)'),stops=[0,.23,.48,.74,1];
 let progress=0,active=-1,manifest=null,frameSource=null,wanted=0,scheduled=false,generation=0,controller=new AbortController(),busy=0;
 const cache=new Map(),pending=new Set(),failed=new Map();
 function draw(){if(!cache.size)return;const key=cache.has(wanted)?wanted:[...cache.keys()].sort((a,b)=>Math.abs(a-wanted)-Math.abs(b-wanted))[0],b=cache.get(key);const ratio=Math.min(devicePixelRatio,2,Math.max(b.width/stage.clientWidth,b.height/stage.clientHeight)),w=Math.round(stage.clientWidth*ratio),h=Math.round(stage.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high'}const scale=Math.max(w/b.width,h/b.height);ctx.drawImage(b,(w-b.width*scale)/2,(h-b.height*scale)/2,b.width*scale,b.height*scale);canvas.style.opacity='1'}
 function queue(){if(!manifest||reduce.matches)return;const token=generation;for(const [i,b]of cache)if(Math.abs(i-wanted)>12){b.close();cache.delete(i)}const near=[wanted,...Array.from({length:7},(_,i)=>wanted+i+1),...Array.from({length:3},(_,i)=>wanted-i-1)];for(const i of near){if(busy>=3)break;if(i<0||i>=manifest.count||cache.has(i)||pending.has(i)||(failed.get(i)?.attempts>=3||failed.get(i)?.retryAt>Date.now()))continue;busy++;pending.add(i);frameSource(i).then(createImageBitmap).then(b=>{if(token!==generation||Math.abs(i-wanted)>12){b.close();return}failed.delete(i);cache.set(i,b);schedule()}).catch(e=>{if(token===generation&&e.name!=='AbortError'){const attempts=(failed.get(i)?.attempts||0)+1;failed.set(i,{attempts,retryAt:Date.now()+attempts*400});if(attempts<3)setTimeout(()=>{if(token===generation)queue()},attempts*400+10)}}).finally(()=>{if(token!==generation)return;busy--;pending.delete(i);queue()})}}
 function update(){scheduled=false;const travel=story.offsetHeight-stage.offsetHeight;progress=reduce.matches?0:Math.max(0,Math.min(1,-story.getBoundingClientRect().top/Math.max(1,travel)));const chapter=mobile.matches?(progress>=.74?3:progress>=.48?2:progress>=.23?1:0):(progress>=.65?3:progress>=.40?2:progress>=.30?1:0);
 if(active!==chapter){active=chapter;story.querySelectorAll('.chapter').forEach((e,i)=>{e.classList.toggle('active',i===active);e.inert=i!==active});const base=mobile.matches?storyMedia.mobile.posters:storyMedia.desktop.posters;poster.src=base[active];poster.alt=['Фасад дата-центра TAU CLOUD','Серверный зал TAU CLOUD','Серверная капсула TAU CLOUD','Облачная инфраструктура'][active];story.querySelector('.chapter-counter').innerHTML=`0${active+1} <span>/ 04</span>`}
 const moment=desktopMoment(progress),copy=reduce.matches?0:mobile.matches?(active===0?0:progress>=.94?3:-1):moment.copy;story.querySelectorAll('.chapter').forEach((e,i)=>{e.classList.toggle('active',i===copy);e.inert=i!==copy});stage.dataset.copy=String(copy);stage.dataset.chapter=String(active);stage.dataset.reveal=String(progress>=.94);stage.style.setProperty('--mobile-lift',`${mobile.matches?Math.max(0,Math.min(1,(progress-.74)/.20))*-18:0}%`);story.querySelectorAll('[data-jump]').forEach((b,i)=>{b.classList.toggle('current',i===active);b.setAttribute('aria-pressed',String(i===active));b.querySelector('i').style.transform=`scaleX(${Math.max(0,Math.min(1,(progress-(mobile.matches?stops:[0,.30,.40,.65,1])[i])/((mobile.matches?stops:[0,.30,.40,.65,1])[i+1]-(mobile.matches?stops:[0,.30,.40,.65,1])[i])))})`});
 if(manifest&&!reduce.matches){const local=(progress-stops[active])/(stops[active+1]-stops[active]),hold=mobile.matches?.04:.13,motion=Math.max(0,Math.min(1,(local-hold)/(1-hold-.04))),beat=manifest.beats[active];wanted=Math.round((mobile.matches?(beat[0]+(beat[1]-beat[0])*motion):moment.frame)*(manifest.count-1));draw();queue()}else if(!manifest||reduce.matches)canvas.style.opacity='0';}
 function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(update)}}
 async function select(){generation++;const token=generation;controller.abort();controller=new AbortController();cache.forEach(b=>b.close());cache.clear();pending.clear();failed.clear();busy=0;manifest=null;active=-1;canvas.style.opacity='0';update();if(reduce.matches)return;try{const base=(mobile.matches?storyMedia.mobile:storyMedia.desktop).base;let response=await fetch(`${base}/playback.json`,{signal:controller.signal});if(!response.ok||!response.headers.get('content-type')?.includes('json'))response=await fetch(`${base}/manifest.json`,{signal:controller.signal});if(!response.ok)return;const data=await response.json();if(token!==generation)return;manifest=data;frameSource=createFrameSource(data,controller.signal);schedule()}catch{}}
 mobile.addEventListener('change',select);reduce.addEventListener('change',select);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);addEventListener('pagehide',()=>{generation++;controller.abort();cache.forEach(b=>b.close());cache.clear()});
 story.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>scrollPageTo(story.offsetTop+(mobile.matches?stops[+b.dataset.jump]+.035:[.03,.35,.53,.90][+b.dataset.jump])*(story.offsetHeight-stage.offsetHeight)));select();
}
