import {createFrameSource} from './frame-source.js';
import {scrollPageTo} from './smooth-scroll.js';
import {chapters} from './content.js';
import {createCloudFinale} from './cloud-finale.js';
export function initStory(){
 const story=document.querySelector('#story'),stage=story.querySelector('.stage'),canvas=story.querySelector('#film'),poster=story.querySelector('#poster'),ctx=canvas.getContext('2d');
 const mobile=matchMedia('(max-width:600px)'),reduce=matchMedia('(prefers-reduced-motion:reduce)'),stops=[0,.23,.48,.74,1];
 const cloud=createCloudFinale(stage,reduce);let progress=0,active=-1,manifest=null,frameSource=null,wanted=0,scheduled=false,generation=0,controller=new AbortController(),busy=0;
 const cache=new Map(),pending=new Set(),failed=new Set();
 function draw(){if(!cache.size)return;const key=cache.has(wanted)?wanted:[...cache.keys()].sort((a,b)=>Math.abs(a-wanted)-Math.abs(b-wanted))[0],b=cache.get(key);const ratio=Math.min(devicePixelRatio,mobile.matches?1.25:1.5),w=Math.round(stage.clientWidth*ratio),h=Math.round(stage.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const scale=Math.max(w/b.width,h/b.height);ctx.drawImage(b,(w-b.width*scale)/2,(h-b.height*scale)/2,b.width*scale,b.height*scale);canvas.style.opacity='1'}
 function queue(){if(!manifest||reduce.matches||active===3)return;const token=generation;for(const [i,b]of cache)if(Math.abs(i-wanted)>12){b.close();cache.delete(i)}const near=[wanted,...Array.from({length:7},(_,i)=>wanted+i+1),...Array.from({length:3},(_,i)=>wanted-i-1)];for(const i of near){if(busy>=3)break;if(i<0||i>=manifest.count||cache.has(i)||pending.has(i)||failed.has(i))continue;busy++;pending.add(i);frameSource(i).then(createImageBitmap).then(b=>{if(token!==generation||Math.abs(i-wanted)>12){b.close();return}cache.set(i,b);schedule()}).catch(e=>{if(token===generation&&e.name!=='AbortError')failed.add(i)}).finally(()=>{if(token!==generation)return;busy--;pending.delete(i);queue()})}}
 function update(){scheduled=false;const travel=story.offsetHeight-stage.offsetHeight;progress=reduce.matches?0:Math.max(0,Math.min(1,-story.getBoundingClientRect().top/Math.max(1,travel)));const chapter=progress>=.74?3:progress>=.48?2:progress>=.23?1:0;
 if(active!==chapter){active=chapter;story.querySelectorAll('.chapter').forEach((e,i)=>{e.classList.toggle('active',i===active);e.inert=i!==active});const base=mobile.matches?['/media/mobile-opening.webp','/media/mobile-interior.webp','/media/mobile-capsule.webp','/media/cloud-mobile.webp']:chapters.map(c=>c.image);poster.src=base[active];poster.alt=['Фасад дата-центра TAU CLOUD','Серверный зал TAU CLOUD','Серверная капсула TAU CLOUD','Облачная инфраструктура'][active];story.querySelector('.chapter-counter').innerHTML=`0${active+1} <span>/ 04</span>`}
 stage.dataset.chapter=String(active);story.querySelectorAll('[data-jump]').forEach((b,i)=>{b.classList.toggle('current',i===active);b.setAttribute('aria-pressed',String(i===active));b.querySelector('i').style.transform=`scaleX(${Math.max(0,Math.min(1,(progress-stops[i])/(stops[i+1]-stops[i])))})`});cloud(progress);
 if(manifest&&!reduce.matches&&active!==3){const local=(progress-stops[active])/(stops[active+1]-stops[active]),hold=mobile.matches?.04:.13,motion=Math.max(0,Math.min(1,(local-hold)/(1-hold-.04))),beat=manifest.beats[active];wanted=Math.round((beat[0]+(beat[1]-beat[0])*motion)*(manifest.count-1));draw();queue()}else if(!manifest||reduce.matches)canvas.style.opacity='0';}
 function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(update)}}
 async function select(){generation++;const token=generation;controller.abort();controller=new AbortController();cache.forEach(b=>b.close());cache.clear();pending.clear();failed.clear();busy=0;manifest=null;active=-1;canvas.style.opacity='0';update();if(reduce.matches)return;try{const base=mobile.matches?'/media/sequence-mobile':'/media/sequence';let response=await fetch(`${base}/playback.json`,{signal:controller.signal});if(!response.ok||!response.headers.get('content-type')?.includes('json'))response=await fetch(`${base}/manifest.json`,{signal:controller.signal});if(!response.ok)return;const data=await response.json();if(token!==generation)return;manifest=data;frameSource=createFrameSource(data,controller.signal);schedule()}catch{}}
 mobile.addEventListener('change',select);reduce.addEventListener('change',select);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);addEventListener('pagehide',()=>{controller.abort();cache.forEach(b=>b.close());cache.clear()});
 story.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>scrollPageTo(story.offsetTop+(stops[+b.dataset.jump]+.035)*(story.offsetHeight-stage.offsetHeight)));select();
}
