import {createFrameSource} from './frame-source.js';
import {scrollPageTo} from './smooth-scroll.js';
import {storyMedia} from './content.js';
import {desktopMoment, storyStops} from './story-timeline.js';

export function initStory(){
 const story=document.querySelector('#story'),stage=story.querySelector('.stage'),canvas=story.querySelector('#film'),poster=story.querySelector('#poster'),ctx=canvas.getContext('2d');
 const mobile=matchMedia('(max-width:600px)'),reduce=matchMedia('(prefers-reduced-motion:reduce)'),stops=storyStops;
 let progress=0,active=-1,manifest=null,frameSource=null,wanted=0,scheduled=false,generation=0,controller=new AbortController(),busy=0,direction=1;
 const cache=new Map(),pending=new Set(),failed=new Map(),posters=new Map();
 function preloadPosters(){
  const sources=(mobile.matches?storyMedia.mobile:storyMedia.desktop).posters;
  for(const src of sources){if(posters.has(src))continue;const image=new Image();image.decoding='async';image.src=src;posters.set(src,image);image.decode().catch(()=>{});}
 }
 function draw(){
  // A nearby frame is useful only within the current scene. Otherwise reveal its poster.
  const [start,end]=manifest.beats[active].map(value=>Math.round(value*(manifest.count-1)));
  const key=[...cache.keys()].filter(i=>i>=start&&(active===manifest.beats.length-1?i<=end:i<end)&&Math.abs(i-wanted)<=12).sort((a,b)=>Math.abs(a-wanted)-Math.abs(b-wanted))[0];
  if(key===undefined){canvas.style.opacity='0';return;}
  const b=cache.get(key),ratio=Math.min(devicePixelRatio,2,Math.max(b.width/stage.clientWidth,b.height/stage.clientHeight)),w=Math.round(stage.clientWidth*ratio),h=Math.round(stage.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high'}const scale=Math.max(w/b.width,h/b.height);ctx.drawImage(b,(w-b.width*scale)/2,(h-b.height*scale)/2,b.width*scale,b.height*scale);canvas.style.opacity='1';
 }
 function queue(){if(!manifest||reduce.matches)return;if(mobile.matches){const r=story.getBoundingClientRect(),visible=!document.hidden&&r.bottom>0&&r.top<innerHeight;frameSource.setWindow(wanted,visible);if(!visible)return;}const token=generation;for(const [i,b]of cache)if(Math.abs(i-wanted)>12){b.close();cache.delete(i)}const near=[wanted,...Array.from({length:7},(_,i)=>wanted+(i+1)*direction),...Array.from({length:3},(_,i)=>wanted-(i+1)*direction)];for(const i of near){if(busy>=3)break;if(i<0||i>=manifest.count||cache.has(i)||pending.has(i)||(failed.get(i)?.attempts>=3||failed.get(i)?.retryAt>Date.now()))continue;busy++;pending.add(i);frameSource(i).then(createImageBitmap).then(b=>{if(token!==generation||Math.abs(i-wanted)>12){b.close();return}failed.delete(i);cache.set(i,b);schedule()}).catch(e=>{if(token===generation&&e.name!=='AbortError'){const attempts=(failed.get(i)?.attempts||0)+1;failed.set(i,{attempts,retryAt:Date.now()+attempts*400});if(attempts<3)setTimeout(()=>{if(token===generation)queue()},attempts*400+10)}}).finally(()=>{if(token!==generation)return;busy--;pending.delete(i);queue()})}}
 function update(){scheduled=false;const travel=story.offsetHeight-stage.offsetHeight;progress=reduce.matches?0:Math.max(0,Math.min(1,-story.getBoundingClientRect().top/Math.max(1,travel)));const chapter=progress>=stops[3]?3:progress>=stops[2]?2:progress>=stops[1]?1:0;
 if(active!==chapter){active=chapter;story.querySelectorAll('.chapter').forEach((e,i)=>{e.classList.toggle('active',i===active);e.inert=i!==active});const base=mobile.matches?storyMedia.mobile.posters:storyMedia.desktop.posters;poster.src=base[active];poster.alt=['Фасад дата-центра TAU CLOUD','Резервное питание TAU CLOUD','Серверные капсулы TAU CLOUD','Операторская и серверный зал TAU CLOUD'][active];story.querySelector('.chapter-counter').innerHTML=`0${active+1} <span>/ 04</span>`}
 const moment=desktopMoment(progress),copy=reduce.matches?0:mobile.matches?(active===0?0:active):moment.copy;story.querySelectorAll('.chapter').forEach((e,i)=>{e.classList.toggle('active',i===copy);e.inert=i!==copy});stage.dataset.copy=String(copy);stage.dataset.chapter=String(active);stage.dataset.reveal=String(progress>=stops[3]);stage.style.setProperty('--mobile-lift',`${mobile.matches?Math.max(0,Math.min(1,(progress-stops[3])/(1-stops[3])))*-12:0}%`);story.querySelectorAll('[data-jump]').forEach((b,i)=>{b.classList.toggle('current',i===active);b.setAttribute('aria-pressed',String(i===active));b.querySelector('i').style.transform=`scaleX(${Math.max(0,Math.min(1,(progress-stops[i])/(stops[i+1]-stops[i])))})`});
 if(manifest&&!reduce.matches){const local=(progress-stops[active])/(stops[active+1]-stops[active]),hold=mobile.matches?.03:.04,motion=Math.max(0,Math.min(1,(local-hold)/(1-hold-.03))),beat=manifest.beats[active];const previous=wanted;wanted=Math.round((mobile.matches?(beat[0]+(beat[1]-beat[0])*motion):moment.frame)*(manifest.count-1));if(wanted!==previous)direction=wanted>previous?1:-1;draw();queue()}else if(!manifest||reduce.matches)canvas.style.opacity='0';}
 function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(update)}}
 async function select(){generation++;const token=generation;controller.abort();controller=new AbortController();cache.forEach(b=>b.close());cache.clear();pending.clear();failed.clear();busy=0;manifest=null;active=-1;canvas.style.opacity='0';update();if(reduce.matches)return;try{const base=(mobile.matches?storyMedia.mobile:storyMedia.desktop).base;let response=await fetch(`${base}/playback.json`,{signal:controller.signal});if(!response.ok||!response.headers.get('content-type')?.includes('json'))response=await fetch(`${base}/manifest.json`,{signal:controller.signal});if(!response.ok)return;const data=await response.json();if(token!==generation)return;if(mobile.matches){await poster.decode().catch(()=>{});if(token!==generation)return}manifest=data;frameSource=createFrameSource(data,controller.signal,{mobile:mobile.matches});schedule()}catch{}}
 mobile.addEventListener('change',preloadPosters);preloadPosters();
 mobile.addEventListener('change',select);reduce.addEventListener('change',select);addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',schedule);addEventListener('pagehide',()=>{generation++;controller.abort();cache.forEach(b=>b.close());cache.clear()});
 story.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>scrollPageTo(story.offsetTop+(stops[+b.dataset.jump]+.025)*(story.offsetHeight-stage.offsetHeight)));select();
}
